### PR TITLE
Show BlockUI only in installer

### PR DESCRIPTION
**Pull request by vwallfahrer**
Regarding 
- https://bugzilla.suse.com/show_bug.cgi?id=965784 
- https://github.com/crowbar/barclamp-crowbar/pull/1380

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
backported from https://github.com/crowbar/crowbar-core/pull/295

**Comment by vuntz** [comment]
@vwallfahrer can you drop the first commit (which is https://github.com/crowbar/barclamp-crowbar/pull/1382)?

**Comment by rhafer** [comment]
> can you drop the first commit

Yes, please. It doesn't work and the other part of the change is good IMO.

**Comment by jsuchome** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
