### PR TITLE
make logging more consistent

### PR DESCRIPTION
**Pull request by MaximilianMeister**
right now logging is a bit inconsistent. 
see for example `AR:` vs `apply_role` as a prefix for the logging output of `service_object.rb`
some time ago i even had to ask what `AR` means, it was not so clear.
one way to generalize it is rubys magic `__method__` which just gives you the name of the method, where the statement is executed.
this would have to be done for the other barclamps as well.

### CODE REVIEW

**Comment by aspiers** [comment]
This is a really nice idea but I think it should really be done by a helper.  That way we can change the format everywhere just by changing one place.  Of course this will make it a bit more difficult since `__method__` cannot be used directly.  But it is still possible to do.

**Comment by aspiers** [comment]
To clarify, I'm thinking of an API something like:

    @logger.mdebug "foo"

where `m` stands for "method".

**Comment by tboerger** [comment]
I don't like this approach. I would prefer the already intergrated tagged loghing functionality: http://api.rubyonrails.org/classes/ActiveSupport/TaggedLogging.html

**Comment by MaximilianMeister** [comment]
@aspiers @tboerger agreed.
closing this, as there are better ways to do this

**Pull request closed without merging**
