### PR TITLE
Keep openvswitch enabled and disable apache

### PR DESCRIPTION
**Pull request by rhafer**

### CODE REVIEW

**Comment by aplanas** [comment]
ahm, not sure about the apache one, is this enabled after the upgrade?

**Comment by jsuchome** [comment]
+1 for apache2, but does disabling openvswitch-switch really hurt? Do you lose the connection after the node reboot?

**Comment by rhafer** [comment]
> ahm, not sure about the apache one, is this enabled after the upgrade

The horizon barclamp will take care of that.

**Comment by rhafer** [comment]
> but does disabling openvswitch-switch really hurt?

I think it depends a lot on the actual network configuration. It just seems to be safer (and more consistent) to not disable it.

**Comment by jsuchome** [comment]
OK then. +1

**Comment by aplanas** [comment]
+1

**Pull request merged**
