### PR TITLE
Preserve ownership of files during backup

### PR DESCRIPTION
**Pull request by rhafer**
Backuport of relevant part of https://github.com/crowbar/crowbar-core/pull/233
from master.

### CODE REVIEW

**Comment by jsuchome** [comment]
+1

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Comment by rhafer** [comment]
This is currently breaking the backup/restore proceduere. I am going to revert it for now. Untill we fixed that.

**Pull request merged**
