### PR TITLE
Fix performance issue w/ slow UI responses

### PR DESCRIPTION
**Pull request by bkutil**
This fixes the performance issues caused by missing HTTP response headers.

Also included is a patch that reduces the app server workers startup time, effectively reducing the time-to-first-response.

### CODE REVIEW

**Comment by vuntz** [comment]
I'll trust you on this, +1 :-)

**Comment by bkutil** [comment]
@vuntz you don't have to - you can test for yourself https://github.com/bkutil/slow-rainbows

**Comment by vuntz** [comment]
Note that you need to change https://github.com/crowbar/barclamp-crowbar/blob/master/chef/cookbooks/crowbar/files/default/config.ru too

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
