### PR TITLE
Exclude SLE12 platform.

### PR DESCRIPTION
**Pull request by aplanas**
Depends on crowbar/barclamp-crowbar#1175

### CODE REVIEW

**Comment by tboerger** [comment]
Do we really want to exclude that hard?

**Comment by aplanas** [comment]
@tboerger We are using this as a reference to decide what to exclude: https://etherpad.nue.suse.com/p/roles

**Comment by jsuchome** [comment]
+1

**Comment by tboerger** [comment]
Does this constraint really make sense here? You can not drag and drop any role anyway here.

**Comment by aplanas** [comment]
@tboerger This is also my opinion, based on my limited knowledge, but I found it useful for documentation.

So, is safe to remove the constraint here?

**Comment by vuntz** [comment]
I would actually leave it for consistency. But it's true that it doesn't matter much.

**Comment by aplanas** [comment]
* Exclude Windows platforms

**Comment by aplanas** [comment]
* Add "count" and "admin" constraints for completeness.

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
