### PR TITLE
Revert all other commits related to "disable 15-minute chef-client run"

### PR DESCRIPTION
**Pull request by vuntz**
Since we reverted that feature, let's just revert all the other commits that were required for it and that add nothing useful.

This obsoletes https://github.com/crowbar/barclamp-crowbar/pull/1286.

### CODE REVIEW

**Comment by aspiers** [comment]
No strong objection but I wonder if this is going to introduce extra conflicts when I backport https://github.com/crowbar/crowbar-core/pull/14

**Comment by vuntz** [comment]
> No strong objection but I wonder if this is going to introduce extra conflicts when I backport crowbar/crowbar-core#14

We said we wouldn't backport that one to stoney ;-)

**Comment by aspiers** [comment]
Oh OK then :)

**Comment by vuntz** [comment]
Any review?

**Comment by rsalevsky** [comment]
LGTM

**Comment by dirkmueller** [comment]
+1 (assuming we can get gating to pass on this)

**Comment by dirkmueller** [comment]
gating is blocked on https://github.com/SUSE-Cloud/automation/pull/588

**Comment by mjura** [comment]
+1 from me too, I was reverting those changes on SC4 too, otherwise I hit errors

**Pull request merged**
