### PR TITLE
Fix array_string_field function

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by tboerger** [comment]
@mjura What about writing a better commit message?

**Comment by mjura** [comment]
Please check if it is more suitable comment

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
The Problem still exists, I run last week in this issue and opened https://bugzilla.suse.com/show_bug.cgi?id=925475 .

**Comment by vuntz** [comment]
@rsalevsky does the commit fix it?

**Comment by rsalevsky** [comment]
@mjura Can you rebase the branch? Then I will test it.

**Comment by bkutil** [comment]
@rsalevsky it applies cleanly, so it does not have to be rebased for testing.

**Comment by rsalevsky** [comment]
Works :+1:

**Pull request merged**
