### PR TITLE
Add .ruby-version and coverage to .gitignore

### PR DESCRIPTION
**Pull request by bkutil**
Re-submitting #1267 .

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by aspiers** [comment]
Thanks.  Slightly curious why you didn't just re-open #1267, but no matter.

**Comment by bkutil** [comment]
> Thanks.  Slightly curious why you didn't just re-open #1267, but no matter.

Because the branch was already deleted and the undo was disabled for
some (unknown) reason.

**Comment by aspiers** [comment]
Yeah, I saw you deleted the branch - maybe that's why it didn't allow re-opening.

**Pull request merged**
