### PR TITLE
i18n: fix missing translation in vanilla crowbar

### PR DESCRIPTION
**Pull request by MaximilianMeister**
translation missing: en.barclamp.show_index.blockui_message

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by bkutil** [comment]
I don't see the string used in the _show_index view, maybe I'm looking at the wrong place, though?

**Comment by bkutil** [comment]
Ah, sorry, it is part of the proposals_helper's create_proposal_form_for

**Comment by bkutil** [comment]
+1

**Comment by MaximilianMeister** [comment]
it's part of proposals_helper.rb

**Comment by MaximilianMeister** [comment]
oops too late

**Pull request merged**
