### PR TITLE
Proposals are no longer in a databag, but in a database now

### PR DESCRIPTION
**Pull request by MaximilianMeister**
@vuntz This was forgotten. I just realized that now :)

@bkutil can you have a look if the code is fine? I haven't had the time to test it

### CODE REVIEW

**Comment by vuntz** [comment]
Ouch, yes. LGTM.

**Comment by tboerger** [comment]
LGTM

**Comment by bkutil** [comment]
So, this has been tested?

**Comment by MaximilianMeister** [comment]
@vuntz @bkutil This is tested now, added another small fix.

```
sqlite> select properties from proposals where barclamp = "heat";

{"id":"bc-heat-default","description":"Installation for Heat","attributes":{"heat":{"debug":false,"verbose":true,"max_header_line":16384,"rabbitmq_instance":"default","database_instance":"default","stack_domain_admin":"heat_domain_admin","stack_domain_admin_password":"fMW53jvIA23W","keystone_instance":"default","service_user":"heat","service_password":"eGx2w8TgaZbr","auth_encryption_key":"fILUZPkm6OmSH63bSARLCYuKf6pA4ugW1ww6","default_instance_user":"ec2-user","api":{"protocol":"http","cfn_port":8000,"engine_port":8001,"cw_port":8003,"port":8004},"db":{"password":"6nD2phrgK9L2","user":"heat","database":"heat"}}},"deployment":{"heat":{"crowbar-revision":0,"crowbar-applied":true,"schema-revision":21,"element_states":{"heat-server":["readying","ready","applying"]},"elements":{"heat-server":["d52-54-01-77-77-01.emil.suse.de"],"heat-server_remove":["d52-54-01-77-77-01.emil.suse.de"]},"element_order":[["heat-server"]],"element_run_list_order":{"heat-server":101},"config":{"environment":"heat-config-default","mode":"full","transitions":false,"transition_list":[]},"crowbar-committing":false,"crowbar-status":"success","crowbar-failed":"","crowbar-queued":true}}}

#### here is apply_role when deactivating heat

sqlite> select properties from proposals where barclamp = "heat";

{"id":"bc-heat-default","description":"Installation for Heat","attributes":{"heat":{"debug":false,"verbose":true,"max_header_line":16384,"rabbitmq_instance":"default","database_instance":"default","stack_domain_admin":"heat_domain_admin","stack_domain_admin_password":"fMW53jvIA23W","keystone_instance":"default","service_user":"heat","service_password":"eGx2w8TgaZbr","auth_encryption_key":"fILUZPkm6OmSH63bSARLCYuKf6pA4ugW1ww6","default_instance_user":"ec2-user","api":{"protocol":"http","cfn_port":8000,"engine_port":8001,"cw_port":8003,"port":8004},"db":{"password":"6nD2phrgK9L2","user":"heat","database":"heat"}}},"deployment":{"heat":{"crowbar-revision":0,"crowbar-applied":true,"schema-revision":21,"element_states":{"heat-server":["readying","ready","applying"]},"elements":{"heat-server":["d52-54-01-77-77-01.emil.suse.de"]},"element_order":[["heat-server"]],"element_run_list_order":{"heat-server":101},"config":{"environment":"heat-config-default","mode":"full","transitions":false,"transition_list":[]},"crowbar-committing":false,"crowbar-status":"success","crowbar-failed":"","crowbar-queued":true}}}
```

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
LGTM codewise

**Comment by bmwiedemann** [comment]
:+1: tested it

**Pull request merged**
