### PR TITLE
add ActiveRecord migration level to the metadata

### PR DESCRIPTION
**Pull request by MaximilianMeister**
partial backport of https://github.com/crowbar/crowbar-core/pull/343

### CODE REVIEW

**Comment by vuntz** [comment]
Hrm, we don't have a db in the backup?

**Comment by MaximilianMeister** [comment]
> Hrm, we don't have a db in the backup?

no, as there is nothing besides maybe the migrations that is worth to backup. and if we would backup the migrations table it would be more effort I think...

**Comment by vuntz** [comment]
@MaximilianMeister sorry, I wasn't clear: is it correct to put a migration level in the backup while we have no db in the backup?

**Comment by MaximilianMeister** [comment]
> is it correct to put a migration level in the backup while we have no db in the backup?

hmm not so sure anymore, in https://github.com/crowbar/crowbar-core/pull/343/files#diff-408ac208d889893305de65518aa046a2R179 it would fall back to `ActiveRecord::Migrator.last_migration.version` if we don't add it here, which I guess should be fine at that point.

if we add it here, it would instead migrate down to that added level and up again to `ActiveRecord::Migrator.last_migration.version` (which would have been the fallback without this patch) which doesn't make too much sense... do you agree?

**Comment by vuntz** [comment]
It feels to me that both should work fine, but I'm not 100% sure. This just needs to be tried. If possible, I'd prefer to avoid further changes here as we already submitted the update to enable 5->6 upgrade.

**Comment by MaximilianMeister** [comment]
>  I'd prefer to avoid further changes here as we already submitted the update to enable 5->6 upgrade.

then let's close this for now

**Pull request closed without merging**
