### PR TITLE
Feature/rails4

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by tboerger** [comment]
Please keep the gemversions like it is.

**Comment by dirkmueller** [comment]
@tboerger care to elaborate on why?

**Comment by tboerger** [comment]
As i already said on another pull request. I have not done it that way just for fun.

**Comment by tboerger** [comment]
Just to keep it the same behavior overall add all fixed versions.

**Comment by tboerger** [comment]
This one can get closed on favor of https://github.com/crowbar/barclamp-crowbar/pull/1194

**Pull request closed without merging**
