### PR TITLE
Make replaceSpace replace all whitespaces, not just space

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by tboerger** [comment]
@mjura Explain it better in commit message please :)

**Comment by rsalevsky** [comment]
:+1: works great, from my side the commit message is clear enough

**Comment by vuntz** [comment]
@rsalevsky maybe you can clarify why it's needed, then? :-) I'm still unsure why this is the case.

**Comment by rsalevsky** [comment]
`\s` matches every whitespace including tabs and linebreaks. Another improvement here is we are independent from the encoding.

**Comment by vuntz** [comment]
I understand the `\s` bit. I'm just not sure that we should also replace `\s*,\s*` as there's no explanation of why it's needed and it changes the function to do more than what its name tells us.

**Comment by mjura** [comment]
@vuntz  : The problem is that when somebody will provide data in following format `string1, string2, string3`, then this will be transformed into `string1,,string2,,string3` which makes validation error for attributes.

**Comment by vuntz** [comment]
@mjura: surely it's a bug in splitString, then, not in this function.

**Comment by mjura** [comment]
@vuntz : In my opinion this regexp should be fixed here, because it parses fields and prepares it for splitString function where `,` are only used as delimiters. But I don't insist, it is only proposal of problem which I have found.

**Comment by vuntz** [comment]
It really depends if "foo,,,,bar" should be split to ["foo", "", "", "", "bar"] or ["foo", "bar"]. I think it should be the latter, hence me thinking we should fix splitString. But if the former is what we expect, then your fix is right.

**Comment by aspiers** [comment]
> It really depends if "foo,,,,bar" should be split to ["foo", "", "", "", "bar"] or ["foo", "bar"].

FWIW, Ruby, Python, and Perl all return the former, and that makes more sense to me, e.g. think of parsing CSV records with empty fields.

**Comment by vuntz** [comment]
>> It really depends if "foo,,,,bar" should be split to ["foo", "", "", "", "bar"] or ["foo", "bar"].
>
>FWIW, Ruby, Python, and Perl all return the former, and that makes more sense to me, e.g. think of parsing CSV records with empty fields.

In a general context, yes. But I'm not sure we care about empty elements in the context of this function here.

Anyway, I guess I'll leave it up to others to share their feelings on this. I'm happy being overruled here.

(I still believe the commit message can be clearer, though ;-))

**Comment by vuntz** [comment]
> (I still believe the commit message can be clearer, though ;-))

Just to be a bit more constructive, I'd split the commit in two commits, and use these messages:

```
Make replaceSpace replace all whitespaces, not just space
```

and

```
Change replaceSpace to also take into accounts commas

We do not want "foo, bar" to be split in ["foo", "", "bar"] but ["foo", "bar"].
```

**Comment by mjura** [comment]
Added new commit and comments changed

**Comment by bkutil** [comment]
+1

**Comment by rsalevsky** [comment]
still :+1:

**Comment by tboerger** [comment]
Got no strong opinion on that anymore. +1

**Comment by mjura** [comment]
Thank you guys :)

**Pull request merged**
