### PR TITLE
Better handling for _remove roles

### PR DESCRIPTION
**Pull request by vuntz**
This is based on work from @MaximilianMeister in https://github.com/crowbar/barclamp-crowbar/pull/1224

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
The removal part looks much better now, the other changes also make sense as far as i can judge. anyways i gave it a test run in terms of `_remove` roles in the runlist, and it worked just fine. I didn't test all changes here though.

**Comment by MaximilianMeister** [comment]
:+1: from my side. and thanks for stepping in here

**Comment by rsalevsky** [comment]
Codewise +1 but needs a rebase

**Comment by vuntz** [comment]
Rebased, needs some careful review again as there were lots of conflicts...

**Comment by MaximilianMeister** [comment]
what were the conflicts? i haven't had any obvious ones at least while testing this.

**Comment by vuntz** [comment]
@MaximilianMeister the merge of https://github.com/crowbar/barclamp-crowbar/pull/1308 created tons of conflicts :-)

**Comment by MaximilianMeister** [comment]
@vuntz Oh I see... you mean merge conflicts :-)

**Comment by vuntz** [comment]
@MaximilianMeister @rsalevsky are your +1 still valid (and this can be merged), or do you want to review again?

**Comment by rsalevsky** [comment]
Still +1

**Comment by MaximilianMeister** [comment]
as I have tested the basic functionality and nothing broke :) i am fine with it

**Pull request merged**
