### PR TITLE
documentation for crowbar batch

### PR DESCRIPTION
**Pull request by aspiers**
https://trello.com/c/8ntaSRJ4

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by tboerger** [comment]
If you integrate it into ```crowbar_framework/doc``` it gets automaticly integrated into the upstream online documentation within the crowbar UI.

**Comment by aspiers** [comment]
@tboerger AFAIK that only became true when they implemented it in the early days of Crowbar 2, and I don't see any evidence of that anywhere. Please can you give more details?  What tree structure are you talking about?

**Comment by tboerger** [comment]
You have never seen that because you are not working in the git based source. Our RPM's are replacing the full upstream documentation that got revamped by me for stoney. The markdown files added to ```crowbar_framework/doc``` folder and to ```crowbar_framework/doc/crowbar.yml``` are getting integrated into the help page within crowbar.

**Comment by tboerger** [comment]
https://github.com/crowbar/barclamp-crowbar/blob/master/crowbar_framework/app/controllers/docs_controller.rb

**Comment by aspiers** [comment]
OK so it's still totally unfinished according to https://github.com/crowbar/barclamp-crowbar/tree/master/crowbar_framework/doc/default/crowbar - I looked at that and assumed it wasn't used at all.

**Comment by tboerger** [comment]
Of course it have to be improved as currently nobody takes care of it. But i think it's a nice place to start :)

**Comment by aspiers** [comment]
This is one of several areas where we are reinventing the wheel thanks to the fork of OpenCrowbar :-(  This was done in Crowbar 2 a long time ago.  Oh well ...

**Comment by tboerger** [comment]
Feel free to migrate to opencrowbar :P

**Comment by dirkmueller** [comment]
so from what I can see we can still merge this as is, right? LGTM

**Comment by aspiers** [comment]
I've just rebased and moved the `batch.md` file to be under `crowbar_framework/doc/default/crowbar/` as suggested by @tboerger; however I didn't update `crowbar_framework/doc/crowbar.yml` because I don't know how that's supposed to work.  We can do that later if it makes sense.

So yes I think this should be fine to merge now.

**Comment by tboerger** [comment]
Fine with me. Hopefully we will get back to better docs generator later. :+1:

**Comment by aspiers** [comment]
I'm just wondering if it's OK to violate DRY here, considering the same doc is now in the deployment guide:

http://docserv.nue.suse.com/documents/Cloud5/susecloud-deployment/html/app.deploy.crowbatch.html

Is it worth having the same thing in two locations?

**Comment by vuntz** [comment]
@aspiers this is really upstream doc vs downstream doc. It's worth it.

**Comment by aspiers** [comment]
OK then :)

**Pull request merged**
