### PR TITLE
Allow ohai 6.24.x

### PR DESCRIPTION
**Pull request by dirkmueller**
Also sync requirements between Gemfile and config/boot.rb

### CODE REVIEW

**Comment by tboerger** [comment]
:-1: It's ok to update gem versions but let's keep the simple versioning in boot.rb because this get's used for our packages only, so if the matching package have been installed.

**Comment by dirkmueller** [comment]
@tboerger it doesn#t look like the versioning gets used at all in config/boot.rb, since it was wrong and nothign seems to have complained about it. how about we simply remove it to not duplicate versioning?

**Comment by tboerger** [comment]
It IS used. It's used in the case of packaging only (as we are not installing Gemfile, it's only installed with crowbar-barclamp-crowbar-devel). So these part of boot.rb makes definitly sense. It's not just a joke from my side ;)

**Comment by tboerger** [comment]
The versioning of boot.rb should stay as it can use totally wrong versions if somebody installs a more current version. Even if it's just by accident.

**Comment by rsalevsky** [comment]
Please rebase

**Comment by tboerger** [comment]
Still :-1: as stated above.

**Comment by dirkmueller** [comment]
@tboerger as seen in https://github.com/crowbar/barclamp-crowbar/pull/1319 the enforcement was not effective before.

**Comment by tboerger** [comment]
> @tboerger as seen in #1319 the enforcement was not effective before.

It have been effective, but this was just a typo as the ```version:``` key was missing.

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by tboerger** [comment]
Even if the boot.rb change is not a hard requirement.

**Pull request merged**
