### PR TITLE
Partial revert of c97aa58c0c68c547e45510320fd19b

### PR DESCRIPTION
**Pull request by rhafer**
Don't show blockui on every click. Partial fix for
https://bugzilla.suse.com/show_bug.cgi?id=965784

### CODE REVIEW

**Comment by rhafer** [comment]
This is just meant as a hotfix to be able to work with the UI again until have a real fix for https://bugzilla.suse.com/show_bug.cgi?id=965784

**Comment by rhafer** [comment]
cc @jsuchome @vwallfahrer

**Comment by jsuchome** [comment]
Yes, this manual check also worked for me. 
+1 unless we find correct solution quickly ( @rsalevsky , @tboerger ?)

**Comment by rsalevsky** [comment]
+1 

We `click` seams to be too global, @vwallfahrer you need to restrict it just to the page where you need it.

**Comment by MaximilianMeister** [comment]
could you have a look at https://github.com/crowbar/crowbar-core/pull/295 ?

I have added a commit which makes it possible to set the blockUI only for certain events and selectors. this should  fix it i guess, when we backport it to cloud5

**Comment by jsuchome** [comment]
@rhafer could you fix the commit message typo ('parital')? Than you can merge it, unless we want to wait for @MaximilianMeister backport

**Comment by rhafer** [comment]
> could you fix the commit message typo ('parital')? Than you can merge it, 

done

**Pull request merged**
