### PR TITLE
eventually use CROWBAR_PORT from the environment

### PR DESCRIPTION
**Pull request by MaximilianMeister**
in the development environment you may want to use a different port

### CODE REVIEW

**Comment by rsalevsky** [comment]
-1 We have already the `--port` option.

**Comment by MaximilianMeister** [comment]
@rsalevsky and why shouldn't you be able to set it via an the environment? and why is it set like this in `crowbar_machines` as well?

**Comment by rsalevsky** [comment]
Having both makes no sense and cause confusion, maybe also conflicts with other variables due to they are global. In general we should use less ENV variables as possible.

`crowbar_machines` is a other topic the new client will use correct parameters

**Comment by aspiers** [comment]
> Having both makes no sense and cause confusion, maybe also conflicts with other variables due to they are global. In general we should use less ENV variables as possible.

In general I totally disagree - supporting both CLI options and environment variables is a very common pattern.  git and the openstack CLI are just two of many examples of very well-known software which does this.  It makes plenty of sense, especially to avoid repeating having to specify the same CLI options over and over again.  The concern about name conflicts does not apply due to the `CROWBAR_` prefix.

It's important to note that the CLI option should always take precedence over the corresponding environment variable - again this is conventional and makes more sense since it allows setting the defaults in the environment and then overriding on the CLI only when necessary.

**Comment by tboerger** [comment]
This should be obsolete with crowbar-client but :+1: as it doesnt hurt.

**Comment by MaximilianMeister** [comment]
rebased to the port 80 change

**Comment by MaximilianMeister** [comment]
okay...  **un**rebased to the port 80 change...

**Comment by vuntz** [comment]
+1

**Pull request merged**
