### PR TITLE
[stoney] Backport of #1251

### PR DESCRIPTION
**Pull request by MaximilianMeister**
https://github.com/crowbar/barclamp-crowbar/pull/1251
https://trello.com/c/zj87VaeB/196-3-p4-bnc-857375-disable-15-minutes-chef-client-run-during-proposal-application

### CODE REVIEW

**Comment by bkutil** [comment]
+1

**Comment by vuntz** [comment]
Please use `cherry-pick -x`for cherry-picking patches.

**Comment by MaximilianMeister** [comment]
@vuntz done

**Comment by tboerger** [comment]
+1

**Comment by jdsn** [comment]
merging as of 2 +1s

**Pull request merged**
