### PR TITLE
[tex] backport add missing chef files

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
waiting for https://github.com/crowbar/crowbar-core/pull/236 to be reviewed

**Comment by rhafer** [comment]
+1

**Comment by MaximilianMeister** [comment]
@vuntz @rhafer the previous gating was green, and I just took out one file from the backup filemap... see https://github.com/crowbar/barclamp-crowbar/commit/b96632de236ef6d8f92025262e8a055d015a7c25

**Comment by MaximilianMeister** [comment]
rebased... maybe that helps

**Comment by aplanas** [comment]
gating fail not related: binding for port da18e46c-205a-496c-8846-06b40d1f07a9 failed.

this check will be removed from c5

**Comment by MaximilianMeister** [comment]
> gating fail not related

can we merge this then?

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
