### PR TITLE
Remove ProposalObject model and associated sync methods

### PR DESCRIPTION
**Pull request by bkutil**

### CODE REVIEW

**Comment by aspiers** [comment]
Travis failure aside, :-1: since there is no commit message body.  That's always needed, but even more so when making fundamental architectural changes.  I realise that this PR is against a feature branch rather than `master`, but I don't think that justifies breaking the rule.

**Comment by tboerger** [comment]
Beside the failing tests I'm fine with that. IMHO it does not require further explanation.

**Comment by aspiers** [comment]
This looks much better now, thanks!  However I think you still need to adjust `bin/crowbar_reset`, which will break due to using `knife` rather than the `crowbar_*` CLI / API (yes that's dumb and it's my fault - sorry).

**Comment by bkutil** [comment]
@aspiers thats a good point. Do you know if there are any other scripts/places in code, that could be using knife instead of the API?

**Comment by aspiers** [comment]
I can't see any off-hand, but I guess we'll notice if something breaks ...  In contrast, when we move the nodes model to the database, we'll have to do more (try `grep -r knife /opt/dell/bin`).

**Comment by bkutil** [comment]
@aspiers could you please help me a bit? which API operations correspond to the knife + options passed to it?

**Comment by aspiers** [comment]
Hmm good point, actually there aren't any APIs for fixing a broken state machine ;-)  So I guess this needs to be ported to manually frob the SQL database instead.

**Comment by bkutil** [comment]
Ok, same question :) I'm not sure, what do the knife commands do? What
would be an equivalent SQL/ActiveRecord query?

**Comment by tboerger** [comment]
@bkutil You have to edit the attributes JSON, for proposal reset you need to set the ```crowbar-committing``` attribute back to ```false```, and for nodes reset you need to set the role ```state``` attribute back to ```ready```, nothing more happens for that.

**Comment by tboerger** [comment]
I think it should be fairly easy to integrate these methods into the API.

**Comment by aspiers** [comment]
They shouldn't be in the API, they are workarounds for internal bugs.

**Comment by bkutil** [comment]
@aspiers which bugs?

**Comment by tboerger** [comment]
Than do some rake tasks? Or just port the existing bin script to interact with the models.

**Comment by aspiers** [comment]
@bkutil https://bugzilla.suse.com/show_bug.cgi?id=840255

> Or just port the existing bin script to interact with the models.

Yes that was my suggestion too.  It could either directly tweak the SQL db, or do it via the Rails models, which would be a lot nicer.  I don't see a big advantage in providing that via Rake tasks over a crowbar CLI subcommand, though.

**Comment by vuntz** [comment]
+1 for the current code, but based on the comments, there's still some bits left to complete.

**Comment by bkutil** [comment]
@aspiers @tboerger Do you think adding something like this to the script would be sufficient?

```bash
cmd="p = Proposal.where(barclamp: '"$bc"', name: '"$proposal"').first || raise; p['deployment']['"$bc"']['crowbar-committing'] = false; p.save;"

pushd "$RAILS_ROOT"
RAILS_ENV=production rails r "$cmd"
popd
```

**Comment by aspiers** [comment]
That sounds reasonable to me.  Of course it would be a lot nicer to ditch the bash and do this in pure Ruby, but for a first pass I think I'm OK with this.

**Comment by aspiers** [comment]
... but only if you do proper line-breaking on the `cmd` assignment!  That long line is *horrible* (it even causes a horizontal scrollbar on this PR review page).

**Comment by bkutil** [comment]
@aspiers @tboerger updated the script to use Rails models instead of knife.

**Comment by aspiers** [comment]
LGTM.

**Pull request merged**
