### PR TITLE
Update package installation list here as well

### PR DESCRIPTION
**Pull request by dirkmueller**
I'm not sure there is really a lot of use for
this right now here since crowbar-barclamp-crowbar should have
the right dependencies already, but I don't want to play
with that right now.

### CODE REVIEW

**Comment by tboerger** [comment]
:-1: uglifier is still used.

**Comment by dirkmueller** [comment]
during runtime? but uglifier depends on execjs which depends on nodejs.. I thought thats what you're trying to change with the precompile step ?

**Comment by tboerger** [comment]
Currently it's still part of the Gemfile and boot.rb, the problem with the runtime dependency is not resolved for barclamp-crowbar for now.

**Comment by dirkmueller** [comment]
hmm. okay.

**Comment by vuntz** [comment]
@tboerger can you revisit this one and review it again?

**Comment by tboerger** [comment]
@vuntz now it makes sense to add rubygem-closure-compiler instead of rubygem-uglifier-2_2.

**Comment by dirkmueller** [comment]
@tboerger closure-compiler was already in the list. Resolved merge conflict (it seems somebody else was able to get in the same patch than I originally proposed)

**Comment by tboerger** [comment]
@dirkmueller yeah, it has been part of tje asset precompile pull request.

**Comment by tboerger** [comment]
I habe not checked if the list got synced full against the Gemfile, but as long as it is in sync i give my +1

**Comment by tboerger** [comment]
@vuntz you merged too fast. I ahve checked the gems now and we are misssing ```i18n-js``` and ```rack-mini-profiler```.

**Pull request merged**
