### PR TITLE
License keys no longer shown in clear text

### PR DESCRIPTION
**Pull request by mschnitzer**
The license keys for windows will now show as passwords.

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by vuntz** [comment]
I don't see the field to edit the license key anymore when picking the Windows as target platform.

**Comment by vuntz** [comment]
also, typo in the commit message: s/shown/show/

**Comment by tboerger** [comment]
> I don't see the field to edit the license key anymore when picking the Windows as target platform.

Are you sure? He just changed it to a password field.

**Comment by vuntz** [comment]
@tboerger I'm sure, I tried it :-)

**Comment by mschnitzer** [comment]
Yes, I forgot the case if the node is already allocated.
Please have a look again: https://github.com/crowbar/barclamp-crowbar/pull/1223/files#diff-6608cea03bc9af95d5065d183b54ecbdR24

**Comment by vuntz** [comment]
Still doesn't work. I need this patch to make it work:

```
--- app/views/nodes/_form.html.haml.old 2015-02-11 09:21:09.000000000 +0100
+++ app/views/nodes/_form.html.haml     2015-02-11 09:20:19.000000000 +0100
@@ -26,11 +26,12 @@
       - else
         .form-group
           = f.label :target_platform, t('.target_platform')
-          = select_tag :target_platform, platforms_for_select(@node.target_platform), :class => "form-control", "data-showit" => [crowbar_service.require_license_platforms.join(","), crowbar_service.support_software_raid.join(",")].join(";"), "data-showit-target" => "#license_key;#raid_type,#raid_disks"
+          = select_tag :target_platform, platforms_for_select(@node.target_platform), :class => "form-control", "data-showit" => [crowbar_service.require_license_platforms.join(","), crowbar_service.support_software_raid.join(",")].join(";"), "data-showit-target" => "#license_key_container;#raid_type,#raid_disks"
 
         .form-group
-          = f.label :license_key, t('.license_key')
-          = password_field_tag :license_key, @node.license_key, :class => "form-control"
+          #license_key_container
+            = f.label :license_key, t('.license_key')
+            = password_field_tag :license_key, @node.license_key, :class => "form-control"
 
       - if crowbar_options[:show].include? :bios
         .form-group
```

**Comment by mschnitzer** [comment]
Are you sure? I tested it 2 hours ago and it worked fine.

**Comment by tboerger** [comment]
@vuntz but ```#license_key_container``` doesn't make sense

**Comment by vuntz** [comment]
@tboerger maybe try the patch?

**Comment by tboerger** [comment]
Please try to replace

```
<select class="form-control" data-showit-target="#license_key;#raid_type,#raid_disks" data-showit="windows-6.3,windows-6.2;suse-12.0,suse-11.3" id="target_platform" name="target_platform">
```

with

```
<select class="form-control" data-showit-target=".toggle-password-wrapper;#raid_type,#raid_disks" data-showit="windows-6.3,windows-6.2;suse-12.0,suse-11.3" id="target_platform" name="target_platform">
```

**Comment by tboerger** [comment]
https://github.com/mschnitzer/barclamp-crowbar/blob/licensekey_fix/crowbar_framework/app/views/nodes/_form.html.haml#L29

**Comment by mschnitzer** [comment]
OK, It's working with the patch vincent provided.

**Comment by vuntz** [comment]
Tested, +1.

**Pull request merged**
