### PR TITLE
No need for specific gem version on travis anymore

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
@bkutil Do you have any idea why it fails? https://rubygems.org/gems/chef/versions shows that there are far more newer versions than chef 10.26, and the version constraint is set to ```~> 10.24```. And for the gem version, we are running ```2.2.2``` and travis installs ```2.2.0```.

**Comment by tboerger** [comment]
So, https://github.com/chef/chef/blame/10-stable/chef/lib/chef/provider/package/rubygems.rb#L37-L41 this have been changed a few days after release of ```10.26```, so we need at least a more current version of chef. Why is it installing ```10.26``` instead of ```10.34```?

**Comment by tboerger** [comment]
So travis succeeds now. Merge? :)

**Comment by bkutil** [comment]
This patch is good, although it might be better to wait w/ the merge after release - just so that some change between 10.26 and 10.34 does not cause regression. What do you think?

**Comment by tboerger** [comment]
I think merging this should be no issue as we are anyway running on a more current version. I will increase the version exactly to our version.

**Comment by vuntz** [comment]
+1 (because this matches the version we're using)

**Comment by bkutil** [comment]
I see, fine w/ me then.

**Pull request merged**
