### PR TITLE
[tex] Update README to direct to the new crowbar-core repo for master

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
-0.5 please mention that this repository only accepts bugfixes for old versions up to tex. And maybe we should remove the master branch.

**Comment by MaximilianMeister** [comment]
@tboerger better now? i want to make the others as well now, once you are good with this one.

**Comment by tboerger** [comment]
Just the replacement of crowbar-core with barclamp-crowbar is missing :)

**Comment by ovisan** [comment]
:+1:

**Comment by MaximilianMeister** [comment]
@tboerger thanks. done

**Pull request merged**
