### PR TITLE
Do not allocate node if target platform is disabled / not available

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by bkutil** [comment]
@vuntz maybe a helper method for the NodeObject.disabled_platform.include?(self.platform), something like `platform_available?` or `platform_enabled?` might make th e checks more readable?

**Comment by bkutil** [comment]
The test fails because the platform checks fail for that particular node. You could either make sure the setup is right (available_platforms includes the node's platform), or move the checks to helpers, and then stub them to make them pass.

**Comment by rsalevsky** [comment]
I would prefer to close the PR if you have not enough time to work on it.

**Comment by rsalevsky** [comment]
@vuntz, this repository got merged into [crowbar-core](https://github.com/crowbar/crowbar-core).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by rsalevsky** [comment]
Cloud 5 (Tex) is EOL since 15th may if this patch is still required please open a new pull request.

**Pull request closed without merging**
