### PR TITLE
Some smaller crowbar cookbook improvements

### PR DESCRIPTION
**Pull request by tboerger**
* Get rid of writing config.ru, the same file is already part of the repository
* Remove unused ```rainbows_path``` variable

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by MaximilianMeister** [comment]
needs a rebase

**Comment by tboerger** [comment]
Rebased

**Comment by vuntz** [comment]
Still +1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
