### PR TITLE
Fixed version requirement of active_model_serializers within boot.rb

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by bkutil** [comment]
+1

**Comment by bmwiedemann** [comment]
seems to be good, but I dont know much about that part

**Comment by bkutil** [comment]
@bmwiedemann this is a typo fix. the line is missing a `version` key, it should look like the others, but does not.

**Comment by tboerger** [comment]
> +0.5 seems to be good, but I dont know much about that part

Without that fix it's simply not preparing the correct active_model_serializer gem version :)

**Comment by MaximilianMeister** [comment]
there are still some more spots

**Comment by MaximilianMeister** [comment]
:+1:

**Comment by tboerger** [comment]
> there are still some more spots

Fixed

**Comment by MaximilianMeister** [comment]
+2.5 merging

**Pull request merged**
